import os
from models.ngram import NGram


def train_ngram(fpath: str | os.PathLike, 
                context: int, 
                lines_to_gen:int=10, 
                spath_text: str | os.PathLike="./generated-text-ngram", 
                spath_model: str | os.PathLike="./trained-models-statedicts"
                ):
    """Train an N-gram model, and display a certain number of lines of text.
    
    Parameters
    ----------
        fpath : str | os.PathLike
            Path to data on which the model will be trained.
        context : int
            Size of the n-gram context window (i.e. the value of "n" in "n-gram")
        lines_to_gen : int
            The number of lines of text to be generated by the model at test time.
        spath_text : str | os.PathLike
            The path at which text generated by the model will be saved.
        spath_model : str | os.PathLike 
            The path at which the model's probability matrix will be saved.
    """
    
    print("\n")
    print(f"{context}-GRAM MODEL")
    print("------")
    ngram = NGram(fpath=fpath, context=context)
    ngram.generate_text(lines_to_gen=lines_to_gen)
    ngram.save_text(f"{spath_text}/{context}-gram.txt")
    ngram.save_model(f"{spath_model}/{context}-gram.npy")
    print("\n")
    print("------")